# Generated by Django 5.0.3 on 2024-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bins', '0002_alter_bin_bin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
